services:
  - type: web
    name: moneymentor-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn app.main:app --reload --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
    healthCheckPath: /health
